#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: strapi
  name: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  strategy: { }
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: strapi
    spec:
      volumes:
        - name: strapi-config
          configMap:
            name: strapi-config
        - name: strapi-bootstrap
          configMap:
            name: strapi-bootstrap
      containers:
        - name: strapi
          image: strapi:latest
          command: [ "/bin/sh" ]
          args:
            - "-c"
            - |
              /usr/local/bin/docker-entrypoint.sh strapi;
              mkdir -p /srv/tmp;
              cp /srv/scripts/strapi_configure.sh /srv/tmp/;
              chmod u+x /srv/tmp/strapi_configure.sh;
              /srv/tmp/strapi_configure.sh;
              cp /stash/bootstrap.js /srv/app/config/functions/;
              strapi develop
          ports:
            - name: http-port
              protocol: TCP
              containerPort: 1337
          livenessProbe:
            httpGet:
              path: /
              port: http-port
            initialDelaySeconds: 450
            periodSeconds: 10
            failureThreshold: 5
          envFrom:
            - secretRef:
                name: strapi-env-secret
          volumeMounts:
            - mountPath: /srv/scripts
              name: strapi-config
            - mountPath: /stash
              name: strapi-bootstrap
          resources: { }
status: { }
