# Copyright SecureKey Technologies Inc.
#
# SPDX-License-Identifier: Apache-2.0

.PHONY: all
all: clean bdd-test

.PHONY: bdd-test
bdd-test:
	@make bdd-test -C ./ace

.PHONY: clean
clean:
	make clean -C ./ace
