#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oathkeeper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oathkeeper
subjects:
- kind: ServiceAccount
  name: default
