#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Adds namespace to all resources.
#namespace: edge-sandbox-system

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
commonLabels:
  component: cms
  group: demo
  instance: local
  project: trustbloc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../common
- strapi/ingress.yml
- oathkeeper/ingress.yml

replacements:
- path: oathkeeper/replacements.yml
  source: null
  targets: null
- path: strapi/replacements.yml
  source: null
  targets: null
- source:
    kind: Secret
    name: cms-wildcard-cert
    version: v1
  targets:
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: oathkeeper-proxy
  - fieldPaths:
    - spec.tls.0.secretName
    select:
      kind: Ingress
      name: strapi

transformers:
- sedtransform.yml
- sedb64transform.yml

secretGenerator:
- files:
  - certs/tls.crt
  - certs/tls.key
  name: cms-wildcard-cert
  type: kubernetes.io/tls

configMapGenerator:
- files:
  - certs/ca.crt
  name: oathkeeper-ca-cert

patchesStrategicMerge:
- oathkeeper/update-local-cert-store.yml
