# Copyright SecureKey Technologies Inc.
#
# SPDX-License-Identifier: Apache-2.0

swagger: "2.0"
info:
  title: Confidential Storage Hub
  description: Confidential Storage Hub
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
schemes:
  - http
  - https
paths:
  /hubstore/profiles:
    post:
      description: Create new profile.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: request
          in: body
          required: true
          schema:
            $ref: "#/definitions/Profile"
      responses:
        201:
          description: New profile.
          headers:
            Location:
              description: Location of the new Profile.
              type: string
          schema:
            $ref: "#/definitions/Profile"
        500:
          description: Generic Error
          schema:
            $ref: "#/definitions/Error"
  /hubstore/profiles/{profileID}/queries:
    parameters:
      - name: profileID
        in: path
        description: The profile's ID.
        required: true
        type: string
    post:
      description: Store queries.
      consumes:
        - application/json
      parameters:
        - name: request
          in: body
          schema:
            $ref: "#/definitions/Query"
      responses:
        201:
          description: Query stored.
          headers:
            Location:
              description: Location of the query resource.
              type: string
        400:
          description: Bad request.
          schema:
            $ref: "#/definitions/Error"
        500:
          description: Generic Error
          schema:
            $ref: "#/definitions/Error"
  /hubstore/profiles/{profileID}/authorizations:
    parameters:
      - name: profileID
        in: path
        description: The profile's ID.
        type: string
        required: true
    post:
      description: Creates a new authorization.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: request
          in: body
          required: true
          schema:
            $ref: "#/definitions/Authorization"
      responses:
        201:
          description: The new authorization.
          headers:
            Location:
              description: Location of the authorization.
              type: string
          schema:
            $ref: "#/definitions/Authorization"
        500:
          description: Generic Error
          schema:
            $ref: "#/definitions/Error"
  /compare:
    post:
      description: Evaluates an operator with its inputs and returns the result.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: request
          in: body
          required: true
          schema:
            $ref: "#/definitions/ComparisonRequest"
      responses:
        200:
          description: Result.
          schema:
            $ref: "#/definitions/Comparison"
        500:
          description: Generic error.
          schema:
            $ref: "#/definitions/Error"
  /extract:
    post:
      description: Extracts the contents of documents.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: request
          in: body
          required: true
          schema:
            type: array
            items:
              $ref: "#/definitions/Query"
            minItems: 1
      responses:
        200:
          description: The extracted and decrypted documents.
          schema:
            $ref: "#/definitions/ExtractionResponse"
        500:
          $ref: "#/definitions/Error"
definitions:
  Profile:
    type: object
    required:
      - controller
    properties:
      id:
        type: string
      controller:
        type: string
      zcap:
        type: string
  ComparisonRequest:
    type: object
    properties:
      op:
        $ref: "#/definitions/Operator"
  Comparison:
    description: TODO - "comparison" does not sound apt as a name
    type: object
    properties:
      result:
        type: boolean
  Operator:
    type: object
    required:
      - type
    discriminator: type
    properties:
      type:
        type: string
  EqOp:
    allOf:
      - $ref: "#/definitions/Operator"
      - type: object
        required:
          - args
        properties:
          args:
            type: array
            items:
              $ref: "#/definitions/Query"
            minItems: 2
  Query:
    type: object
    required:
      - type
    discriminator: type
    properties:
      id:
        type: string
      type:
        type: string
  DocQuery:
    allOf:
      - $ref: "#/definitions/Query"
      - type: object
        required:
          - vaultID
          - docID
          - upstreamAuth
        properties:
          vaultID:
            type: string
          docID:
            type: string
          path:
            type: string
          upstreamAuth:
            type: object
            required:
              - edv
              - kms
            properties:
              edv:
                $ref: "#/definitions/UpstreamAuthorization"
              kms:
                $ref: "#/definitions/UpstreamAuthorization"
  RefQuery:
    allOf:
      - $ref: "#/definitions/Query"
      - type: object
        required:
          - ref
        properties:
          ref:
            type: string
  Authorization:
    type: object
    required:
      - requestingParty
      - scope
    properties:
      id:
        type: string
      requestingParty:
        type: string
      scope:
        type: object
        required:
          - resourceID
          - resourceType
          - action
        properties:
          resourceID:
            type: string
          resourceType:
            type: string
          action:
            type: array
            items:
              type: string
              enum:
                - read
                - reference
          caveats:
            type: array
            items:
              $ref: "#/definitions/Caveat"
      zcap:
        type: string
  UpstreamAuthorization:
    type: object
    properties:
      baseURL:
        type: string
      zcap:
        type: string
  Caveat:
    type: object
    required:
      - type
    discriminator: type
    properties:
      type:
        type: string
  ExpiryCaveat:
    allOf:
      - $ref: "#/definitions/Caveat"
      - type: object
        properties:
          duration:
            type: integer
            description: Duration (in seconds) for which this authorization will remain valid.
  ExtractionResponse:
    type: array
    items:
      properties:
        id:
          type: string
        document:
          type: object
  Error:
    type: object
    properties:
      errMessage:
        type: string
